### ISSUE TITLE
cpu usage almost 90%

### ISSUE THREAD

**Issue by irwinai** [maroslaw/rainyday.js#133]
hi,i just found a problem,
when use the js and keep the page always open
the cpu usage will be grew up to almost 90%
I think this is a serious problem for you

**Comment by Codewyvern** [comment]
On ipad 3 the library is completely unusable, its just chugging along at snails pace, however on a quad core home desktop its perfect, why is it so slow? what is slowing it down so much? I just can't believe my ipad can play fully 3D games and then suffers from a few raindrops.

**Comment by TheRune** [comment]
actually that's exactly the difference. Your iPad has hardware accellerated 2D and 3D rendering, which is used by games, but this script doesn't use it, which makes a big difference on a device with a somewhat limited CPU

**Comment by Codewyvern** [comment]
Ah ok, I assumed that canvas rendering used the GPU, I guess not. So is there a way to actually use the GPU like WebGL or something?

**Comment by mubaidr** [comment]
This issue is fixed in latest build of Chrome (As it uses gpu acceleration for rendering in Canvas.).
