### ISSUE TITLE
Avoiding z-index issue

### ISSUE THREAD

**Issue by mubaidr** [maroslaw/rainyday.js#139]
~~There are two possible ways to fix z-index issue;~~

1) Insert new canvas element with same z-index and right next to original Image.

~~2) Original image should be hidden and Canvas (with same z-index as original image) could be used to render original image and raindrops.~~

Only the first option will work, 2 option will fail or cause issues when there is content after that image at same z-index level!

**Comment by sergmed** [comment]
does not work. write a piece of code. please
