### ISSUE TITLE
How to stop rainyday?

### ISSUE THREAD

**Issue by petrospap** [maroslaw/rainyday.js#154]
Hello, I use rainyday in https://simply4all.net/pop-corn/
with similar way as you have in your examples.
How to stop rainyday after successful start to run?
can you provide any idea how to delete engine to stop run rain?
Thank you!

**Comment by Koroba** [comment]
That's a great question.

**Comment by wloske** [comment]
I am having the same issue. Anyone?

**Comment by interglobalmedia** [comment]
I'll take the question further: is there a way of making the rain stop when it's good weather or doing something other than raining and start up again when it is raining? I'll look into the stop() method as well. Otherwise, I do love this plugin. Thanks!

**Comment by wloske** [comment]
@interglobalmedia I  do not know if this is a serious request, but it should be no problem to connect the RainyDay to some weather API ... as I said, I'd give the refactored version a try. It provides a `stop()` method and if all works this should be enough to what you are looking for ...

**Comment by ohabash** [comment]
can you help me with the `stop()`.... Cant figure out how to use it

**Comment by mubaidr** [comment]
There are methods available to `pause` and `resume` already. I will be adding `destroy` method too.

**Comment by mubaidr** [comment]
https://github.com/mubaidr/rainyday.js
