### ISSUE TITLE
Using my own background image

### ISSUE THREAD

**Issue by Mexikaner9** [maroslaw/rainyday.js#160]
Hello
Please tell me how I can use my own background image.
The script is fantastic, but it is useless for me if I can not use my own background image.
Thanks in advance

**Comment by StevOSS** [comment]
Hi Mexikaner9,
just replace this line from **index.html **:

image.src = 'http://i.imgur.com/N7ETzFO.jpg';

with your picture from folder or from server. example:
<img src="assets/img/example.png">

**Comment by StevOSS** [comment]
hi, 
Just replace this line from **index.html**:
image.src = 'http://i.imgur.com/N7ETzFO.jpg';
with whatever you have, for example
<image.src="assets/img/example.jpg">

**Comment by StevOSS** [comment]
image.src = 'image\example.jpg';

**Comment by Mexikaner9** [comment]
Hello
many thanks for your response!
Of course, I've tried to replace this line, but it does not work.
These are my examples: 
http://dauten.server29.vorschauseite.eu/rainyday/ 
http://dauten.server29.vorschauseite.eu/rainyday/index2.html 
Unfortunately, none of these examples work.
Can you please tell me what is wrong?
I do not understand that.
Thank you in advance!
Have a great day

**Comment by interglobalmedia** [comment]
I placed my code that initiates the rainyday,js plugin in a separate JS file along with my other js code, and I added my own background img within the function run() under image.src = "path to your own image";

**Comment by Mexikaner9** [comment]
Thank you for your answer! 
unfortunatelly it doesnt work 
http://dauten.server29.vorschauseite.eu/rainyday/index3.html

**Comment by interglobalmedia** [comment]
You must be doing something wrong somewhere then. This is the link to my repo:

https://github.com/interglobalmedia/rainy-weather

**Comment by Mexikaner9** [comment]
Many thanks for your response!
I've downloaded the rainyday package once again, I made a copy of demo1.html and I opened this file with notepad++ and I added an my own image, but it does not work in Google Chrome, but it works in Internet Explorer. The original file works in Google Chrome. I do not understand that. This is frustrating.

**Comment by StevOSS** [comment]
Mexikaner9

I've checked your work in goog;le chrome and it show your picture and the rainy.js work fine.

**Comment by Mexikaner9** [comment]
O.k.
thank you

**Comment by nunaram** [comment]
I am facing the same problem. It is not working when I am using other images.

**Comment by mubaidr** [comment]
Have anybody tested the new experimental branch?

**Comment by iadec** [comment]
i just tried the experimental branch.. and it doesn't work at all for me.. none of the demo.html files.. was hoping demo6.html was the solution to using your own image.. but i just get - 
![screen shot 2017-10-24 at 1 27 55 pm](https://user-images.githubusercontent.com/27915430/31943047-4fee188e-b8bf-11e7-9cc0-b27d1f1636d2.png)

**Comment by iadec** [comment]
I was using demo.html from master, which works nice.. ..but not too sure why a simple change like 

image.src = './images/beach.jpg';

or

image.src = 'images/beach.jpg';

doesn't work ?

**Comment by mubaidr** [comment]
I have updated readme with new option: https://github.com/mubaidr/rainyday.js#how-to-use

**Comment by iadec** [comment]
I don't see any difference in the readme ..whats the new option ?

**Comment by mubaidr** [comment]
This:

> image: element,         
[Image Id or Image element itself, Id of Element having background Image or Element itself]

**Comment by nunaram** [comment]
It's working perfectly. You have to preview the demos on localhost.

**Comment by mubaidr** [comment]
Great! I am working on updated homepage where all demos can be viewed on-line.

**Comment by iadec** [comment]
@nunaram which demo are you working with that allows you to use your own image ?

@mubaidr yes it is a valid url ? ..its local..

**Comment by mubaidr** [comment]
@iadec Please open devtools and let me the error message.

**Comment by iadec** [comment]
Yup.. if I use an image from Imgur it works.. do we have to use images from that site ? ..whats so special about Imgur ?

**Comment by iadec** [comment]
this works.. https://i.imgur.com/k52yiJh.jpg this doesn't.. yet same image just different hosting site..  https://bbiab.com/images/bg01.jpg

**Comment by mubaidr** [comment]
This is CORS issue (Details: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
In simple words this is not script issue. `bbiab.com` does not allow to load/hot-link images to third party sites unlike imgur. Image is unabel to load, that is why the script does not work.

**Comment by mubaidr** [comment]
Also, i have published new homepage with example using css background as image source. 
https://mubaidr.github.io/rainyday.js/
