### ISSUE TITLE
How to stop and restart everytime rainyday is run()

### ISSUE THREAD

**Issue by ohabash** [maroslaw/rainyday.js#168]
I am using ajax to switch views in my project. Each view has a new background... I successfully set `image.src` dynamically. but that required me to re-run. So now i would like to restart it each time the view changes.

Any advice?

**Comment by ohabash** [comment]
I just removed the canvas before running. I dont know if that was the right way `$('canvas').remove();`

**Comment by mubaidr** [comment]
I Will look into this matter.
