### ISSUE TITLE
Can I Use This On Non-Image Elements

### ISSUE THREAD

**Issue by Iwillbeawebdeveloper** [maroslaw/rainyday.js#171]
Firstly I love what you have done here, I am trying to find an excuse to use it!

I have tried to use it on body and div tags but without success.  Do I have to use it on an image tag?

**Comment by mubaidr** [comment]
Yes, it does require an image because for accuracy/beautification purposes, each n every droplet show reflection of the image behind.

**Comment by Iwillbeawebdeveloper** [comment]
Thanks for your advice

**Comment by mubaidr** [comment]
But the next release will work with background image of any element.
