### ISSUE TITLE
Fix a typo

### ISSUE THREAD

**Issue by IsaacHub** [maroslaw/rainyday.js#172]
@maroslaw 
Kindly fit it.
![chrome_2017-03-16_12-42-03](https://cloud.githubusercontent.com/assets/20126441/23985712/8b814dee-0a46-11e7-97d7-84e4c7748b93.png)

**Comment by mubaidr** [comment]
Can you please mention which page has this?

**Comment by IsaacHub** [comment]
@mubaidr 
It's at the bottom of this page: [http://maroslaw.github.io/rainyday.js/](http://maroslaw.github.io/rainyday.js/)

**Comment by mubaidr** [comment]
Ohh.. Ok Will update.  thanks
