### ISSUE TITLE
my homepage calls up a background image (below).  But rainyday.js refers directly to an image.

### ISSUE THREAD

**Issue by abbrunger** [maroslaw/rainyday.js#173]
Hello,

I would like to use rainyday.js on my homepage.  But my homepage calls up a background image (below).  But rainyday.js refers directly to an image.

How would I connect rainyday.js to the background image below?

.fullscreen-bg {
		position: fixed;
  		top: 0;
  		right: 0;
  		bottom: 0;
  		left: 0;
  		overflow: hidden;
  		z-index: 3;
		background:url(../img/hp/hpdesktop.jpg) center center / cover no-repeat;	
		background-color: #000;
}

**Comment by mubaidr** [comment]
This is work in progress, you can track progress here: https://github.com/maroslaw/rainyday.js/issues/95

**Comment by mubaidr** [comment]
Have you tested the new experimental branch?

**Comment by abbrunger** [comment]
Hello,

Thanks for reaching out.

I apologize, but I am not sure where in #95 the solve is for a CSS
background image (or CSS responsive background image)?

Could you show me specifically where I should be looking in  #95
<https://github.com/maroslaw/rainyday.js/issues/95> ?

Thanks!!

**Comment by abbrunger** [comment]
demo 6 (background image), doesn't seem to work at all?

**Comment by mubaidr** [comment]
Sorry, i need to update read me to reflect updated changes and show new features.

**Comment by mubaidr** [comment]
New option available, demo-6 is fixed. https://github.com/mubaidr/rainyday.js#how-to-use
