### ISSUE TITLE
How to use it in vue.js

### ISSUE THREAD

**Issue by 44886** [maroslaw/rainyday.js#184]
How to use it in vue.js

**Comment by amorist** [comment]
@44886

**Comment by amorist** [comment]
@44886 You have no title to ask for our support

![image](https://user-images.githubusercontent.com/14037268/40839683-2c1ba6c8-65d6-11e8-977d-cba6e810cad6.png)

**Comment by 44886** [comment]
shut up, please.

**Comment by 44886** [comment]
@amorist shut up, please.
