### ISSUE TITLE
Any possibility for rainyday.js to work with a background-image ?

### ISSUE THREAD

**Issue by loicraux** [maroslaw/rainyday.js#95]
As of today, rainyday.js requires an identified <img> element as a target ....
Any possibility for rainyday.js to work with a background-image url in a CSS stylesheet ?
Thanks!

**Comment by gatelli** [comment]
+1 for the background image... any news please ?

**Comment by Xarcell** [comment]
+1

**Comment by Ozzyboshi** [comment]
+1

**Comment by porollo** [comment]
+1

**Comment by shikelong** [comment]
+1

**Comment by yadenisenko** [comment]
+1

**Comment by iffifan** [comment]
we are waiting...
+1 from me as well

**Comment by owentdoyler** [comment]
+1

**Comment by mubaidr** [comment]
I will try to work on this request, expect some update in few days.

**Comment by PeterDaveHello** [comment]
Thanks @mubaidr

**Comment by mubaidr** [comment]
So the first experimental build is available. seems to be working fine. Expect few bugs. 

https://github.com/maroslaw/rainyday.js/tree/experimental

**Comment by mubaidr** [comment]
Fixed the resize issue too.

**Comment by PeterDaveHello** [comment]
Can't wait for the next release 👍

**Comment by mubaidr** [comment]
I am trying to improve the performance of the script. Will release the version soon if no bugs are found.

**Comment by owentdoyler** [comment]
Any updates on this. Is there a stable release that works with background-image yet?

**Comment by mubaidr** [comment]
@owentdoyler pls check the demo-6: https://github.com/mubaidr/rainyday.js/blob/master/demo6.html

Remember to use latest script form this repo: https://github.com/mubaidr/rainyday.js/blob/master/rainyday.js

**Comment by mubaidr** [comment]
I have published new homepage with example using css background as image source.
https://mubaidr.github.io/rainyday.js/
